//! Memory data types.
//!
//! Defines the core structures for the deep memory system:
//! entries, conversation summaries, search results, and nudges.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// A single memory entry — the fundamental unit of the memory system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryEntry {
    /// Unique identifier (UUID v4).
    pub id: String,
    /// Tenant scope.
    pub tenant_id: String,
    /// Session this memory originated from.
    pub session_id: String,
    /// The memory content (summary, fact, or learning).
    pub content: String,
    /// Source type: "conversation", "explicit", "learned", "nudge".
    pub source: MemorySource,
    /// How important this memory is (0.0–1.0). Influences retrieval ranking.
    pub importance: f32,
    /// Categorization tags.
    pub tags: Vec<String>,
    /// Embedding vector (serialized as JSON array).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub embedding: Option<Vec<f32>>,
    /// When the memory was created.
    pub created_at: DateTime<Utc>,
    /// Last time this memory was retrieved.
    pub last_accessed_at: DateTime<Utc>,
    /// Number of times this memory has been retrieved.
    pub access_count: u32,
}

/// Source of a memory entry.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MemorySource {
    /// Auto-generated from conversation.
    Conversation,
    /// User explicitly asked to remember.
    Explicit,
    /// Learned by the system through observation.
    Learned,
    /// Proactive nudge generated by the system.
    Nudge,
}

impl std::fmt::Display for MemorySource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            MemorySource::Conversation => write!(f, "conversation"),
            MemorySource::Explicit => write!(f, "explicit"),
            MemorySource::Learned => write!(f, "learned"),
            MemorySource::Nudge => write!(f, "nudge"),
        }
    }
}

/// A summary of a completed conversation session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConversationSummary {
    /// The session being summarized.
    pub session_id: String,
    /// Tenant scope.
    pub tenant_id: String,
    /// Human-readable summary (1–3 paragraphs).
    pub summary: String,
    /// Key takeaways (bullet points).
    pub key_points: Vec<String>,
    /// Decisions made during the conversation.
    pub decisions: Vec<String>,
    /// When the conversation started.
    pub start_time: DateTime<Utc>,
    /// When the conversation ended.
    pub end_time: DateTime<Utc>,
    /// Number of messages exchanged.
    pub message_count: u32,
}

/// A rolling summary — incremental compression of ongoing session history.
///
/// Unlike `ConversationSummary` (post-mortem), this is updated mid-session
/// by DeepSeek Flash to shrink long contexts for smaller-window models.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RollingSummary {
    /// Session this rolling summary belongs to.
    pub session_id: String,
    /// Tenant scope.
    pub tenant_id: String,
    /// Compressed history — injected into system prompt for small-model routing.
    pub compressed_history: String,
    /// Topic references for RAG recovery: (topic_label, message_ids_json).
    pub topic_index: Vec<TopicRef>,
    /// Total tokens compressed so far (cumulative across all merges).
    pub tokens_compressed: u64,
    /// Iterations since last compression.
    pub iteration_count: u32,
    /// Index of the last message included in compressed_history.
    pub last_message_idx: usize,
    /// When the last merge occurred.
    pub last_compressed_at: DateTime<Utc>,
}

/// A topic reference for RAG-recovery when switching back to a large-context model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TopicRef {
    /// Short topic label (e.g. "database schema", "auth refactor").
    pub label: String,
    /// Comma-separated message IDs that belong to this topic.
    pub message_ids: Vec<String>,
    /// Approximate token count of this topic's messages.
    pub token_estimate: u64,
}

/// A search result returned by the memory retrieval system.
#[derive(Debug, Clone)]
pub struct SearchResult {
    /// The matching memory entry.
    pub entry: MemoryEntry,
    /// Semantic similarity score (0.0–1.0). Cosine similarity to query embedding.
    pub semantic_score: f32,
    /// Recency bonus (0.0–1.0). Newer entries score higher.
    pub recency_score: f32,
    /// Combined score used for ranking.
    pub combined_score: f32,
}

/// A proactive nudge — the system suggests relevant context.
#[derive(Debug, Clone)]
pub struct MemoryNudge {
    /// The nudge content to inject into the agent context.
    pub content: String,
    /// Related memory entries that triggered this nudge.
    pub source_entries: Vec<MemoryEntry>,
    /// How relevant the system thinks this is (0.0–1.0).
    pub confidence: f32,
    /// Time-sensitive? If true, the nudge is prioritized.
    pub urgent: bool,
}

/// Configuration for the memory engine.
#[derive(Debug, Clone)]
pub struct MemoryConfig {
    /// Path to the SQLite database file.
    pub db_path: String,
    /// Maximum number of entries to retrieve per search.
    pub max_retrieval_results: usize,
    /// Minimum similarity score for results (0.0–1.0).
    pub similarity_threshold: f32,
    /// How much recency affects ranking (0.0 = no effect, 1.0 = maximum).
    pub recency_weight: f32,
    /// How much importance affects ranking.
    pub importance_weight: f32,
    /// Whether to auto-summarize conversations when they end.
    pub auto_summarize: bool,
    /// Whether to generate proactive nudges.
    pub nudges_enabled: bool,
    /// Maximum age of entries to consider for retrieval (hours). 0 = unlimited.
    pub max_entry_age_hours: u32,
    /// Skip embedding generation (useful for tests without ONNX model).
    pub skip_embeddings: bool,
}

impl Default for MemoryConfig {
    fn default() -> Self {
        Self {
            db_path: "~/.ohagent/memory.db".to_string(),
            max_retrieval_results: 10,
            similarity_threshold: 0.3,
            recency_weight: 0.3,
            importance_weight: 0.4,
            auto_summarize: true,
            nudges_enabled: true,
            max_entry_age_hours: 720, // 30 days
            skip_embeddings: false,
        }
    }
}
