#!/usr/bin/env bash
set -euo pipefail

# ohAgent dev-start.sh
# Builds and starts both daemon and CLI for local testing.
#
# Usage:
#   ./scripts/dev-start.sh            # start both (build if stale)
#   ./scripts/dev-start.sh --build    # force rebuild before starting
#   ./scripts/dev-start.sh --daemon   # start daemon only
#   ./scripts/dev-start.sh --cli      # start CLI only
#
# Prerequisites:
#   - OPENAI_API_KEY or ANTHROPIC_API_KEY set in environment
#   - ~/.config/ohagent/config.toml (generated by first build if missing)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ohagent"
CONFIG_FILE="$CONFIG_DIR/config.toml"

# Detect config defaults
DEFAULT_MODEL="${DEFAULT_MODEL:-gpt-4o}"
PRIMARY_PROVIDER="${PRIMARY_PROVIDER:-openai}"

ensure_config() {
    if [[ ! -f "$CONFIG_FILE" ]]; then
        echo "🔧 Creating default config at $CONFIG_FILE"
        mkdir -p "$CONFIG_DIR"
        cat > "$CONFIG_FILE" <<EOF
# ohAgent daemon configuration
# Generated by dev-start.sh

[daemon]
host = "127.0.0.1"
port = 8447
telegram_enabled = false

[provider]
name = "$PRIMARY_PROVIDER"
model = "$DEFAULT_MODEL"

[memory]
path = "$CONFIG_DIR/memory.db"
embedding_model = "text-embedding-3-small"

[tools]
enabled = ["bash", "read", "write", "edit", "ls", "grep", "memory"]
git_allowed = true

[logging]
level = "info"
json = false
EOF
        echo "✅ Config written. Edit $CONFIG_FILE to customize."
        echo ""
    fi

    # Warn if no API key
    if [[ -z "${OPENAI_API_KEY:-}" && -z "${ANTHROPIC_API_KEY:-}" ]]; then
        echo "⚠️  WARNING: Neither OPENAI_API_KEY nor ANTHROPIC_API_KEY is set."
        echo "   The daemon will likely fail to make LLM calls."
        echo "   Set one of them in your shell profile or .env file."
        echo ""
    fi
}

build_daemon() {
    echo "🔨 Building ohagent-daemon (release)..."
    cargo build --release -p ohagent-daemon 2>&1
    echo "✅ Daemon built."
}

build_cli() {
    echo "🔨 Building ohagent-cli (release)..."
    cargo build --release -p ohagent-cli 2>&1
    echo "✅ CLI built."
}

start_daemon() {
    echo "🚀 Starting ohagent-daemon..."
    echo "   Config: $CONFIG_FILE"
    echo "   Logs:   $CONFIG_DIR/daemon.log"
    echo ""
    cd "$PROJECT_DIR"
    RUST_LOG="${RUST_LOG:-info}" \
    cargo run --release -p ohagent-daemon 2>&1 | tee "$CONFIG_DIR/daemon.log"
}

start_cli() {
    echo "💬 Starting ohagent-cli..."
    echo "   Connect to ws://127.0.0.1:8447/v1/ws/chat"
    echo ""
    cd "$PROJECT_DIR"
    cargo run --release -p ohagent-cli
}

# --- Main ---

cd "$PROJECT_DIR"
ensure_config

MODE="${1:-both}"

case "$MODE" in
    --build|build)
        build_daemon
        build_cli
        ;;
    --daemon|daemon)
        build_daemon
        start_daemon
        ;;
    --cli|cli)
        build_cli
        start_cli
        ;;
    both|--both|"")
        build_daemon
        build_cli
        echo ""
        echo "═══════════════════════════════════════════════"
        echo "  Starting daemon (background) + CLI (foreground)"
        echo "  Press Ctrl+C to stop both."
        echo "═══════════════════════════════════════════════"
        echo ""
        # Start daemon in background
        RUST_LOG="${RUST_LOG:-info}" \
        cargo run --release -p ohagent-daemon &
        DAEMON_PID=$!
        echo "📡 Daemon PID: $DAEMON_PID"

        # Give it a moment to bind
        sleep 2

        # Start CLI in foreground
        cargo run --release -p ohagent-cli || true

        # Cleanup daemon on exit
        echo ""
        echo "🛑 Stopping daemon (PID $DAEMON_PID)..."
        kill "$DAEMON_PID" 2>/dev/null || true
        wait "$DAEMON_PID" 2>/dev/null || true
        echo "✅ Done."
        ;;
    *)
        echo "Usage: $0 [--build|--daemon|--cli]"
        exit 1
        ;;
esac
