apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ohagent

resources:
  - ../../base

nameSuffix: -dev

patches:
  - target:
      kind: Deployment
      name: ohagent-daemon
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
  - target:
      kind: PersistentVolumeClaim
      name: ohagent-data
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: "local-path"
      - op: replace
        path: /spec/resources/requests/storage
        value: "1Gi"

images:
  - name: rg.pl-waw.scw.cloud/orangehat/ohagent-daemon
    newTag: dev
